create table public.basket
(
    date_create timestamp(6),
    all_price decimal(10.2),
    id          bigint generated by default as identity
        primary key
);

alter table public.basket
    owner to postgres;

create table public.cart
(
    date_time timestamp(6),
    id        bigint generated by default as identity
        primary key
);

alter table public.cart
    owner to postgres;

create table public.role
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
) WITH (
      OIDS = FALSE
    );

alter table public.role
    owner to postgres;

create table public.tree
(
    id        bigint generated by default as identity
        primary key,
    parent_id bigint
        constraint fk_parent_id
            references public.tree
            on delete cascade,
    category  varchar(255)
);

alter table public.tree
    owner to postgres;

create table public.book
(
    count     integer,
    id        bigint generated by default as identity
        primary key,
    node_id   bigint
        constraint fk_node_id
            references public.tree,
    author    varchar(255),
    genre     varchar(255),
    price decimal(10.2),
    delivery integer,
    publisher varchar(255),
    status    varchar(255)
        constraint book_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    title     varchar(255)
);

alter table public.book
    owner to postgres;

create table public.book_basket
(
    quantity  integer,
    priceQuantity decimal(10.2),
    basket_id bigint
        constraint fk_basket_id
            references public.basket,
    book_id   bigint
        constraint fk_book_id
            references public.book,
    id        bigint generated by default as identity
        primary key
);

alter table public.book_basket
    owner to postgres;

create table public.book_cart
(
    book_id       bigint
        constraint fk_book_id
            references public.book,
    cart_id       bigint
        constraint fk_cart_id
            references public.cart,
    delivery_report varchar(255),
    creation_time timestamp(6),
    delivery_report_date timestamp(6),
    report_on_the_event_date timestamp(6),
    status_delivery_id integer,
    id            bigint generated by default as identity
        primary key
);

alter table public.book_cart
    owner to postgres;

create table public.users
(
    basket_id bigint
        unique
        constraint fk_basket_id
            references public.basket,
    cart_id   bigint
        unique
        constraint fk_cart_id
            references public.cart,
    id        bigint generated by default as identity
        primary key,
    email     varchar(255),
    password  varchar(255),
    username  varchar(255)
);

alter table public.users
    owner to postgres;

create table public.users_roles
(
    role_id integer not null
        constraint fk_role_id
            references public.role,
    user_id bigint  not null
        constraint fk_user_id
            references public.users
);

alter table public.users_roles
    owner to postgres;


