create table public.description
(
    id          bigint not null
        primary key,
    category    varchar(255),
    description text,
    title       varchar(255)
);

alter table public.description
    owner to postgres;

create table public.faq
(
    date_answer_create   timestamp(6),
    date_question_create timestamp(6),
    description_id       bigint
        constraint fk_description_id
            references public.description,
    id                   bigint generated by default as identity
        primary key,
    answer               varchar(255),
    question             varchar(255)
);

alter table public.faq
    owner to postgres;
